// seedTemplate.js
require("dotenv").config();
const mongoose = require("mongoose");
const GutterProductTemplate = require("../models/gutterProductTemplate");

// ---- Starter data -----------------------------------------------------------
// If you already maintain this array elsewhere, you can keep it here.
// The only requirement is: items may include `showInProductList`; if omitted,
// we default it to true during seeding.

const starterItems = [
  {
    name: '5" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '5"',
    description:
      'Standard 5" K-Style aluminum gutter for residential installations',
    defaultColor: "#000000",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '6" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '6"',
    description: 'Wider 6" K-Style aluminum gutter for higher water flow areas',
    defaultColor: "#234a38",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '7" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '7"',
    description:
      'Commercial-grade 7" K-Style aluminum gutter for heavy rainfall',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '5" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '5"',
    description: 'Modern aesthetic alternative to 5" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '6" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '6"',
    description: 'Modern aesthetic alternative to 6" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '7" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '7"',
    description: 'Modern aesthetic alternative to 7" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '6" Half-Round Gutter',
    type: "gutter",
    profile: "half-round",
    size: '6"',
    description: 'Traditional 6" half-round copper/aluminum gutter profile',
    defaultColor: "#aa5500",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: '6" Box Gutter',
    type: "gutter",
    profile: "box",
    size: '6"',
    description: "Modern box gutter profile for clean-edge installations",
    defaultColor: "#999999",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: "Custom Profile Gutter",
    type: "gutter",
    profile: "custom",
    size: '6"',
    description: "Non standard gutter profile for a custom job",
    defaultColor: "#999999",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
    showInProductList: true,
  },
  {
    name: "2x3 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "2x3",
    description: "Small residential downspout for light flow areas",
    defaultColor: "#000000",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "3x4",
    description: "Standard size for moderate to heavy rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "4x5 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "4x5",
    description: "Extra large size for very heavy rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3" Round Downspout',
    type: "downspout",
    profile: "round",
    size: '3"',
    description: "Small size downspout for light flow areas",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4" Round Downspout',
    type: "downspout",
    profile: "round",
    size: '4"',
    description:
      "Medium size downspout for modarate to heave rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Box Downspout",
    type: "downspout",
    profile: "box",
    size: "box",
    description:
      "Square or rectangle box downspout that sports custom bends and hard lines",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Smooth Downspout",
    type: "downspout",
    profile: "box",
    size: "box",
    description: "Rectangle 3x4 box downspout that sports a modern look",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Smooth A Elbow",
    type: "accessory",
    profile: "smooth",
    size: "3x4",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Box A Elbow",
    type: "accessory",
    profile: "box",
    size: "",
    description: "A-style elbow for redirecting box downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Box B Elbow",
    type: "accessory",
    profile: "box",
    size: "",
    description: "B-style elbow for redirecting box downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: 'Box 2" Offset',
    type: "accessory",
    profile: "box",
    size: '2"',
    description: "2-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: 'Box 4" Offset',
    type: "accessory",
    profile: "box",
    size: '4"',
    description: "4-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: 'Box 6" Offset',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: "6-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Smooth B Elbow",
    type: "accessory",
    profile: "smooth",
    size: "3x4",
    description: "B-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "2x3 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "2x3 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '2x3 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '2x3 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '2x3 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "3x4 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3x4 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3x4 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3x4 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "4x5 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "4x5 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4x5 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4x5 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4x5 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3" Round Elbow',
    type: "accessory",
    profile: "round",
    size: '3"',
    description: "Round elbow for redirecting downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3" Round 2" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3" Round 4" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '3" Round 6" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4" Round Elbow',
    type: "accessory",
    profile: "round",
    size: '4"',
    description: "Round elbow for redirecting downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4" Round 2" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4" Round 4" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '4" Round 6" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '5" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated corner for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },

  {
    name: '5" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated bay corner for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '5" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated end cap for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated end cap for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Half Round End Cap',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated end cap for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '7" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated end cap for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated corner for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },

  {
    name: '6" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated bay corner for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },

  {
    name: '7" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated corner for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '7" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated bay corner for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Half Round Strip Miter',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated corner for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Half Round Bay Miter',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated bay corner for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Box Miter',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: 'Custom corner for 6" Box gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Box End Cap',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: 'Custom end cap for 6" Box gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Custom End Cap",
    type: "accessory",
    profile: "custom",
    size: 'custom"',
    description: "Custom end cap for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Custom Bay Miter",
    type: "accessory",
    profile: "custom",
    size: "custom",
    description: "Custom bay corner for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: "Custom Strip Miter",
    type: "accessory",
    profile: "custom",
    size: "custom",
    description: "Custom corner for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '5" Straight Face Strip Miter',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom corner for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '5" Straight Face Bay Miter',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom corner for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '5" Straight Face End Cap',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom end cap for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Straight Face Strip Miter',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom corner for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Straight Face Bay Miter',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom corner for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '6" Straight Face End Cap',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom end cap for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '7" Straight Face Strip Miter',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom corner for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '7" Straight Face Bay Miter',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom corner for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
  {
    name: '7" Straight Face End Cap',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom end cap for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },

  {
    name: "Custom Miter",
    type: "accessory",
    profile: "round",
    size: '6"',
    description: "Custom fabricated corner for Custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
    showInProductList: true,
  },
];

// ---- Helpers ----------------------------------------------------------------

// normalize strings
function norm(v) {
  return String(v ?? "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9\-"]/g, "");
}

// stable slug based on key attributes; adjust if you need a different scheme
function slugifyTemplate(t) {
  const parts = [t.type, t.profile, t.size, t.name].map(norm);
  return parts.join("|");
}

// ---- Main seeding logic -----------------------------------------------------

async function main() {
  const uri = process.env.MONGODB_URI || "mongodb://localhost:27017/";
  const dbName = process.env.MONGO_DB || "esti-mate";

  await mongoose.connect(uri, { dbName });
  console.log("[seedTemplate] Connected:", dbName);

  // 1) ensure showInProductList is present (default true)
  const normalized = starterItems.map((item) => ({
    ...item,
    showInProductList: item.showInProductList ?? true,
  }));

  // 2) add slug
  const withSlugs = normalized.map((item) => ({
    ...item,
    slug: slugifyTemplate(item),
    updatedAt: new Date(),
  }));

  // 3) bulk replace by unique name (your existing behavior)
  const ops = withSlugs.map((doc) => ({
    replaceOne: {
      filter: { name: doc.name },
      replacement: doc, // NOTE: replaceOne overwrites doc -> include ALL fields
      upsert: true,
    },
  }));

  const res = await GutterProductTemplate.bulkWrite(ops, { ordered: false });
  console.log("[seedTemplate] bulkWrite result:", {
    upserted: res.upsertedCount,
    modified: res.modifiedCount,
    matched: res.matchedCount,
  });

  await mongoose.disconnect();
  console.log(
    "✅ Templates now match starterItems exactly (incl. showInProductList)."
  );
}

// Export the data (so other scripts can import starterItems safely)
module.exports = { starterItems };

// Only run when invoked directly: `node seedTemplate.js`
if (require.main === module) {
  main().catch((err) => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
  });
}
