const GutterProductTemplate = require("../models/gutterProductTemplate.js");
const DB_URI = "mongodb://localhost:27017/esti-mate";
const mongoose = require("mongoose");

async function seedTemplates() {
  await mongoose.connect(DB_URI);
  console.log("🚀 Connected to db");

  const starterItems = [
    {
      name: '5" K-Style Gutter',
      type: "gutter",
      profile: "k-style",
      size: '5"',
      description:
        'Standard 5" K-Style aluminum gutter for residential installations',
      defaultColor: "#000000",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style Gutter',
      type: "gutter",
      profile: "k-style",
      size: '6"',
      description:
        'Wider 6" K-Style aluminum gutter for higher water flow areas',
      defaultColor: "#234a38",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style Gutter',
      type: "gutter",
      profile: "k-style",
      size: '7"',
      description:
        'Commercial-grade 7" K-Style aluminum gutter for heavy rainfall',
      defaultColor: "#445566",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '5" Straight Face Gutter',
      type: "gutter",
      profile: "straight-face",
      size: '5"',
      description: 'Modern aesthetic alternative to 5" K-Style gutter',
      defaultColor: "#445566",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '6" Straight Face Gutter',
      type: "gutter",
      profile: "straight-face",
      size: '6"',
      description: 'Modern aesthetic alternative to 6" K-Style gutter',
      defaultColor: "#445566",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '7" Straight Face Gutter',
      type: "gutter",
      profile: "straight-face",
      size: '7"',
      description: 'Modern aesthetic alternative to 7" K-Style gutter',
      defaultColor: "#445566",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '6" Half-Round Gutter',
      type: "gutter",
      profile: "half-round",
      size: '6"',
      description: 'Traditional 6" half-round copper/aluminum gutter profile',
      defaultColor: "#aa5500",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: '6" Box Gutter',
      type: "gutter",
      profile: "box",
      size: '6"',
      description: "Modern box gutter profile for clean-edge installations",
      defaultColor: "#999999",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: "Custom Profile Gutter",
      type: "gutter",
      profile: "custom",
      size: '6"',
      description: "Non standard gutter profile for a custom job",
      defaultColor: "#999999",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: true,
      canWrapFascia: true,
      canReplaceFascia: true,
      canReplace1x2: true,
      canBeRemoved: true,
    },
    {
      name: "2x3 Corrugated Downspout",
      type: "downspout",
      profile: "corrugated",
      size: "2x3",
      description: "Small residential downspout for light flow areas",
      defaultColor: "#000000",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 Corrugated Downspout",
      type: "downspout",
      profile: "corrugated",
      size: "3x4",
      description: "Standard size for moderate to heavy rainfall drainage",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "4x5 Corrugated Downspout",
      type: "downspout",
      profile: "corrugated",
      size: "4x5",
      description: "Extra large size for very heavy rainfall drainage",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3" Round Downspout',
      type: "downspout",
      profile: "round",
      size: '3"',
      description: "Small size downspout for light flow areas",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4" Round Downspout',
      type: "downspout",
      profile: "round",
      size: '4"',
      description:
        "Medium size downspout for modarate to heave rainfall drainage",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "Box Downspout",
      type: "downspout",
      profile: "box",
      size: "box",
      description:
        "Square or rectangle box downspout that sports custom bends and hard lines",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 Smooth Downspout",
      type: "downspout",
      profile: "box",
      size: "box",
      description: "Rectangle 3x4 box downspout that sports a modern look",
      defaultColor: "#333333",
      defaultUnit: "foot",
      isDownspout: true,
      hasElbows: true,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 Smooth A Elbow",
      type: "accessory",
      profile: "smooth",
      size: "3x4",
      description: "A-style elbow for redirecting downspouts toward walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 Smooth B Elbow",
      type: "accessory",
      profile: "smooth",
      size: "3x4",
      description: "B-style elbow for redirecting downspouts toward walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "2x3 A Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "2x3",
      description: "A-style elbow for redirecting downspouts toward walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "2x3 B Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "2x3",
      description: "B-style elbow for redirecting downspouts along walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '2x3 2" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "2x3",
      description:
        'Downspout joint that diverts the downspout 2" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '2x3 4" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "2x3",
      description:
        'Downspout joint that diverts the downspout 4" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '2x3 6" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "2x3",
      description:
        'Downspout joint that diverts the downspout 6" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 A Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description: "A-style elbow for redirecting downspouts toward walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "3x4 B Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description: "B-style elbow for redirecting downspouts along walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3x4 2" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description:
        'Downspout joint that diverts the downspout 2" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3x4 4" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description:
        'Downspout joint that diverts the downspout 4" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3x4 6" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description:
        'Downspout joint that diverts the downspout 6" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "4x5 A Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description: "A-style elbow for redirecting downspouts toward walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "4x5 B Elbow",
      type: "accessory",
      profile: "corrugated",
      size: "3x4",
      description: "B-style elbow for redirecting downspouts along walls",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4x5 2" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "4x5",
      description:
        'Downspout joint that diverts the downspout 2" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4x5 4" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "4x5",
      description:
        'Downspout joint that diverts the downspout 4" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4x5 6" Offset',
      type: "accessory",
      profile: "corrugated",
      size: "4x5",
      description:
        'Downspout joint that diverts the downspout 6" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3" Round Elbow',
      type: "accessory",
      profile: "round",
      size: '3"',
      description: "Round elbow for redirecting downspouts",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3" Round 2" Offset',
      type: "accessory",
      profile: "round",
      size: '3"',
      description:
        'Downspout joint that diverts the downspout 2" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3" Round 4" Offset',
      type: "accessory",
      profile: "round",
      size: '3"',
      description:
        'Downspout joint that diverts the downspout 4" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '3" Round 6" Offset',
      type: "accessory",
      profile: "round",
      size: '3"',
      description:
        'Downspout joint that diverts the downspout 6" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4" Round Elbow',
      type: "accessory",
      profile: "round",
      size: '4"',
      description: "Round elbow for redirecting downspouts",
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4" Round 2" Offset',
      type: "accessory",
      profile: "round",
      size: '4"',
      description:
        'Downspout joint that diverts the downspout 2" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4" Round 4" Offset',
      type: "accessory",
      profile: "round",
      size: '4"',
      description:
        'Downspout joint that diverts the downspout 4" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '4" Round 6" Offset',
      type: "accessory",
      profile: "round",
      size: '4"',
      description:
        'Downspout joint that diverts the downspout 6" towards or away from walls',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '5" K-Style Inside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '5"',
      description: 'Prefabricated inside corner for 5" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '5" K-Style Outside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '5"',
      description: 'Prefabricated outside corner for 5" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '5" K-Style Inside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '5"',
      description: 'Prefabricated inside bay corner for 5" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '5" K-Style Outside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '5"',
      description: 'Prefabricated outside bay corner for 5" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '5" K-Style End Cap',
      type: "accessory",
      profile: "k-style",
      size: '5"',
      description: 'Prefabricated end cap for 5" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style End Cap',
      type: "accessory",
      profile: "k-style",
      size: '6"',
      description: 'Prefabricated end cap for 6" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" Half Round End Cap',
      type: "accessory",
      profile: "round",
      size: '6"',
      description: 'Prefabricated end cap for 6" Half Round gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style End Cap',
      type: "accessory",
      profile: "k-style",
      size: '7"',
      description: 'Prefabricated end cap for 7" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style Inside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '6"',
      description: 'Prefabricated inside corner for 6" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style Outside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '6"',
      description: 'Prefabricated outside corner for 6" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style Inside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '6"',
      description: 'Prefabricated inside bay corner for 6" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" K-Style Outside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '6"',
      description: 'Prefabricated outside bay corner for 6" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style Inside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '7"',
      description: 'Prefabricated inside corner for 7" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style Outside Strip Miter',
      type: "accessory",
      profile: "k-style",
      size: '7"',
      description: 'Prefabricated outside corner for 7" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style Inside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '7"',
      description: 'Prefabricated inside bay corner for 7" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '7" K-Style Outside Bay Miter',
      type: "accessory",
      profile: "k-style",
      size: '7"',
      description: 'Prefabricated outside bay corner for 7" K-style gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" Half Round Inside Strip Miter',
      type: "accessory",
      profile: "round",
      size: '6"',
      description: 'Prefabricated inside corner for 6" Half Round gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" Half Round Outside Strip Miter',
      type: "accessory",
      profile: "round",
      size: '6"',
      description: 'Prefabricated outside corner for 6" Half Round gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" Half Round Inside Bay Miter',
      type: "accessory",
      profile: "round",
      size: '6"',
      description: 'Prefabricated inside bay corner for 6" Half Round gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: '6" Half Round Outside Bay Miter',
      type: "accessory",
      profile: "round",
      size: '6"',
      description: 'Prefabricated outside bay corner for 6" Half Round gutters',
      defaultColor: "#000000",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "Micro-Mesh Guard",
      type: "guard",
      profile: "none",
      size: "none",
      description: "Premium micro-mesh guard for small debris and pine needles",
      defaultColor: "#888888",
      defaultUnit: "foot",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "Splash Block",
      type: "accessory",
      profile: "none",
      size: "none",
      description: "Ground-level block to disperse water from downspouts",
      defaultColor: "#777777",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "Rain Chain",
      type: "accessory",
      profile: "none",
      size: "none",
      description: "Decorative chain alternative to the traditional downspout",
      defaultColor: "#777777",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
    {
      name: "Gutter Gate",
      type: "accessory",
      profile: "none",
      size: "none",
      description:
        "Specialized one-way downspout cover for the bottom of a downspout",
      defaultColor: "#888888",
      defaultUnit: "unit",
      isDownspout: false,
      hasElbows: false,
      supportsGutterGuard: false,
      canWrapFascia: false,
      canReplaceFascia: false,
      canReplace1x2: false,
      canBeRemoved: true,
    },
  ];

  let newItems = 0;

  for (const item of starterItems) {
    const exists = await GutterProductTemplate.findOne({
      name: item.name,
    });

    if (!exists) {
      await GutterProductTemplate.create(item);
      newItems++;
      console.log(`✅ Inserted: ${item.name}`);
    } else {
      console.log(`⚠️ Skipped duplicate: ${item.name}`);
    }
  }

  console.log(`Seeded ${newItems} products successfully ✅`);
  process.exit();
}

seedTemplates().catch((err) => {
  console.error("⚠️ Seeding failed", err);
  process.exit(1);
});
