/****************************
 *
 * CONFIG
 ****************************/
const dbName = "esti-mate"; // use current DB; or hardcode: const dbName = "esti-mate";
use(dbName);

// If true, we'll update user color even if they customized (NOT recommended).
const FORCE_UPDATE_USER_COLOR = false;

// If you want to only update unit when the user "inherits" it, set this to true.
// Else we update unit when it's missing/empty.
const REQUIRE_INHERITS_UNIT = false;

/****************************
 * NEW / UPDATED TEMPLATES
 * Paste your new/updated templates here
 ****************************/
const newTemplates = [
  {
    name: '5" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '5"',
    description:
      'Standard 5" K-Style aluminum gutter for residential installations',
    defaultColor: "#000000",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '6" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '6"',
    description: 'Wider 6" K-Style aluminum gutter for higher water flow areas',
    defaultColor: "#234a38",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '7" K-Style Gutter',
    type: "gutter",
    profile: "k-style",
    size: '7"',
    description:
      'Commercial-grade 7" K-Style aluminum gutter for heavy rainfall',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '5" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '5"',
    description: 'Modern aesthetic alternative to 5" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '6" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '6"',
    description: 'Modern aesthetic alternative to 6" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '7" Straight Face Gutter',
    type: "gutter",
    profile: "straight-face",
    size: '7"',
    description: 'Modern aesthetic alternative to 7" K-Style gutter',
    defaultColor: "#445566",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '6" Half-Round Gutter',
    type: "gutter",
    profile: "half-round",
    size: '6"',
    description: 'Traditional 6" half-round copper/aluminum gutter profile',
    defaultColor: "#aa5500",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: '6" Box Gutter',
    type: "gutter",
    profile: "box",
    size: '6"',
    description: "Modern box gutter profile for clean-edge installations",
    defaultColor: "#999999",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: "Custom Profile Gutter",
    type: "gutter",
    profile: "custom",
    size: '6"',
    description: "Non standard gutter profile for a custom job",
    defaultColor: "#999999",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: true,
    canWrapFascia: true,
    canReplaceFascia: true,
    canReplace1x2: true,
    canBeRemoved: true,
    canBeRepaired: true,
  },
  {
    name: "2x3 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "2x3",
    description: "Small residential downspout for light flow areas",
    defaultColor: "#000000",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "3x4",
    description: "Standard size for moderate to heavy rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "4x5 Corrugated Downspout",
    type: "downspout",
    profile: "corrugated",
    size: "4x5",
    description: "Extra large size for very heavy rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3" Round Downspout',
    type: "downspout",
    profile: "round",
    size: '3"',
    description: "Small size downspout for light flow areas",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4" Round Downspout',
    type: "downspout",
    profile: "round",
    size: '4"',
    description:
      "Medium size downspout for modarate to heave rainfall drainage",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Box Downspout",
    type: "downspout",
    profile: "box",
    size: "box",
    description:
      "Square or rectangle box downspout that sports custom bends and hard lines",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Smooth Downspout",
    type: "downspout",
    profile: "box",
    size: "box",
    description: "Rectangle 3x4 box downspout that sports a modern look",
    defaultColor: "#333333",
    defaultUnit: "foot",
    isDownspout: true,
    hasElbows: true,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Smooth A Elbow",
    type: "accessory",
    profile: "smooth",
    size: "3x4",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Box A Elbow",
    type: "accessory",
    profile: "box",
    size: "",
    description: "A-style elbow for redirecting box downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Box B Elbow",
    type: "accessory",
    profile: "box",
    size: "",
    description: "B-style elbow for redirecting box downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: 'Box 2" Offset',
    type: "accessory",
    profile: "box",
    size: '2"',
    description: "2-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: 'Box 4" Offset',
    type: "accessory",
    profile: "box",
    size: '4"',
    description: "4-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: 'Box 6" Offset',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: "6-inch offset fitting for box downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Smooth B Elbow",
    type: "accessory",
    profile: "smooth",
    size: "3x4",
    description: "B-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "2x3 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "2x3 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '2x3 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '2x3 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '2x3 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "2x3",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "3x4 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3x4 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3x4 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3x4 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "3x4",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "4x5 Corrugated A Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description: "A-style elbow for redirecting downspouts toward walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "4x5 Corrugated B Elbow",
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description: "B-style elbow for redirecting downspouts along walls",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4x5 Corrugated 2" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4x5 Corrugated 4" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4x5 Corrugated 6" Offset',
    type: "accessory",
    profile: "corrugated",
    size: "4x5",
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3" Round Elbow',
    type: "accessory",
    profile: "round",
    size: '3"',
    description: "Round elbow for redirecting downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3" Round 2" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3" Round 4" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '3" Round 6" Offset',
    type: "accessory",
    profile: "round",
    size: '3"',
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4" Round Elbow',
    type: "accessory",
    profile: "round",
    size: '4"',
    description: "Round elbow for redirecting downspouts",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4" Round 2" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 2" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4" Round 4" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 4" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '4" Round 6" Offset',
    type: "accessory",
    profile: "round",
    size: '4"',
    description:
      'Downspout joint that diverts the downspout 6" towards or away from walls',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '5" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated corner for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },

  {
    name: '5" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated bay corner for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '5" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '5"',
    description: 'Prefabricated end cap for 5" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated end cap for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Half Round End Cap',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated end cap for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '7" K-Style End Cap',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated end cap for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated corner for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },

  {
    name: '6" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '6"',
    description: 'Prefabricated bay corner for 6" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },

  {
    name: '7" K-Style Strip Miter',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated corner for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '7" K-Style Bay Miter',
    type: "accessory",
    profile: "k-style",
    size: '7"',
    description: 'Prefabricated bay corner for 7" K-style gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Half Round Strip Miter',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated corner for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Half Round Bay Miter',
    type: "accessory",
    profile: "round",
    size: '6"',
    description: 'Prefabricated bay corner for 6" Half Round gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Box Miter',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: 'Custom corner for 6" Box gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Box End Cap',
    type: "accessory",
    profile: "box",
    size: '6"',
    description: 'Custom end cap for 6" Box gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Custom End Cap",
    type: "accessory",
    profile: "custom",
    size: 'custom"',
    description: "Custom end cap for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Custom Bay Miter",
    type: "accessory",
    profile: "custom",
    size: "custom",
    description: "Custom bay corner for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Custom Strip Miter",
    type: "accessory",
    profile: "custom",
    size: "custom",
    description: "Custom corner for custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '5" Straight Face Strip Miter',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom corner for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '5" Straight Face Bay Miter',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom corner for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '5" Straight Face End Cap',
    type: "accessory",
    profile: '5"',
    size: '5"',
    description: 'Custom end cap for 5" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Straight Face Strip Miter',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom corner for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Straight Face Bay Miter',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom corner for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '6" Straight Face End Cap',
    type: "accessory",
    profile: '6"',
    size: '6"',
    description: 'Custom end cap for 6" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '7" Straight Face Strip Miter',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom corner for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '7" Straight Face Bay Miter',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom corner for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: '7" Straight Face End Cap',
    type: "accessory",
    profile: '7"',
    size: '7"',
    description: 'Custom end cap for 7" Straight Face gutters',
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },

  {
    name: "Micro-Mesh Guard",
    type: "guard",
    profile: "none",
    size: "none",
    description: "Premium micro-mesh guard for small debris and pine needles",
    defaultColor: "#888888",
    defaultUnit: "foot",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Splash Block",
    type: "accessory",
    profile: "none",
    size: "none",
    description: "Ground-level block to disperse water from downspouts",
    defaultColor: "#777777",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
  {
    name: "Rain Chain",
    type: "accessory",
    profile: "none",
    size: "none",
    description: "Decorative chain alternative to the traditional downspout",
    defaultColor: "#777777",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },

  {
    name: "Custom Miter",
    type: "accessory",
    profile: "round",
    size: '6"',
    description: "Custom fabricated corner for Custom gutters",
    defaultColor: "#000000",
    defaultUnit: "unit",
    isDownspout: false,
    hasElbows: false,
    supportsGutterGuard: false,
    canWrapFascia: false,
    canReplaceFascia: false,
    canReplace1x2: false,
    canBeRemoved: true,
    canBeRepaired: false,
  },
];

function slugFor(tpl) {
  const norm = (s) =>
    (s || "").toString().trim().toLowerCase().replace(/\s+/g, "-");
  return [norm(tpl.type), norm(tpl.profile), norm(tpl.size), norm(tpl.name)]
    .filter(Boolean)
    .join("|");
}

/****************************
 * COLLECTION NAMES
 ****************************/
const TPL = db.gutterproducttemplates; // master catalog/templates
const UGP = db.usergutterproducts; // per-user products
const USERS = db.users; // users collection

/****************************
 * INDEXES (idempotent)
 ****************************/
// Templates by name (safe)
TPL.createIndex({ name: 1 }, { unique: true });

// User products indexes — check first to avoid conflicts
const ugpIndexNames = db.usergutterproducts.getIndexes().map((i) => i.name);

// Ensure the PARTIAL UNIQUE index exists (skip if already there)
if (!ugpIndexNames.includes("userId_1_templateId_1")) {
  UGP.createIndex(
    { userId: 1, templateId: 1 },
    {
      unique: true,
      name: "userId_1_templateId_1",
      partialFilterExpression: {
        userId: { $type: "objectId" },
        templateId: { $type: "objectId" },
      },
    }
  );
}

// Secondary index (safe to re-run)
if (!ugpIndexNames.includes("userId_1_name_1")) {
  UGP.createIndex({ userId: 1, name: 1 }, { name: "userId_1_name_1" });
}

/****************************
 * UPSERT TEMPLATES
 ****************************/
const nameToTemplateId = new Map();

newTemplates.forEach((tpl) => {
  const res = TPL.updateOne(
    { name: tpl.name },
    {
      $set: {
        // fields that can change over time
        type: tpl.type,
        profile: tpl.profile,
        size: tpl.size,
        description: tpl.description,
        defaultColor: tpl.defaultColor,
        defaultUnit: tpl.defaultUnit,
        isDownspout: tpl.isDownspout,
        hasElbows: tpl.hasElbows,
        supportsGutterGuard: tpl.supportsGutterGuard,
        canWrapFascia: tpl.canWrapFascia,
        canReplaceFascia: tpl.canReplaceFascia,
        canReplace1x2: tpl.canReplace1x2,
        canBeRemoved: tpl.canBeRemoved,
        canBeRepaired: tpl.canBeRepaired,
        updatedAt: new Date(),
      },
      $setOnInsert: {
        createdAt: new Date(),
      },
    },
    { upsert: true }
  );

  // Find the doc so we get _id regardless of upsert path
  const doc = TPL.findOne({ name: tpl.name }, { _id: 1 });
  nameToTemplateId.set(tpl.name, doc._id);
});

/****************************
 * PER-USER UPSERT + SYNC
 ****************************/
const users = USERS.find({}, { _id: 1 }).toArray();

users.forEach((user) => {
  newTemplates.forEach((tpl) => {
    const templateId = nameToTemplateId.get(tpl.name);

    // Try find existing user product
    const existing = UGP.findOne({
      userId: user._id,
      templateId: templateId,
    });

    if (!existing) {
      // Insert brand-new user product from template
      UGP.insertOne({
        userId: user._id, // <-- use userId
        templateId: templateId, // <-- link to template

        name: tpl.name,
        type: tpl.type,
        profile: tpl.profile,
        size: tpl.size,
        slug: slugFor(tpl), // <-- ensure slug exists

        description: tpl.description,
        color: tpl.defaultColor,
        unit: tpl.defaultUnit,

        price: 1,
        inheritsColor: true,
        inheritsUnit: true,

        createdAt: new Date(),
        updatedAt: new Date(),
      });
      print(`Inserted user product '${tpl.name}' for user ${user._id}`);
    } else {
      // Build a selective update that respects user customizations
      const update = { $set: { updatedAt: new Date() } };

      // Always sync name/type/profile/size/description to keep metadata current
      update.$set.name = tpl.name;
      update.$set.type = tpl.type;
      update.$set.profile = tpl.profile;
      update.$set.size = tpl.size;
      update.$set.description = tpl.description;
      update.$set.slug = slugFor(tpl);

      // Sync unit conditionally
      const shouldUpdateUnit =
        (REQUIRE_INHERITS_UNIT &&
          (existing.inheritsUnit === true ||
            existing.unit == null ||
            existing.unit === "")) ||
        (!REQUIRE_INHERITS_UNIT &&
          (existing.unit == null || existing.unit === ""));

      if (shouldUpdateUnit) {
        update.$set.unit = tpl.defaultUnit;
        if (existing.inheritsUnit === undefined) {
          update.$set.inheritsUnit = true;
        }
      }

      // Sync color conditionally
      const userAllowsColorInherit = FORCE_UPDATE_USER_COLOR
        ? true
        : existing.inheritsColor === true;

      if (userAllowsColorInherit) {
        update.$set.color = tpl.defaultColor;
        if (existing.inheritsColor === undefined) {
          update.$set.inheritsColor = true;
        }
      }

      UGP.updateOne({ _id: existing._id }, update);
      print(`Updated user product '${tpl.name}' for user ${user._id}`);
    }
  });
});

print("Done.");
